apiVersion: v1
appVersion: v0.7.0
description: Open Cluster Management.
engine: gotpl
home: https://github.com/kubernetes/ingress-nginx
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
keywords:
- ingress
- nginx
kubeVersion: '>=1.10.0-0'
maintainers:
- name: ChiefAlexander
- email: Trevor.G.Wood@gmail.com
  name: taharah
name: open-cluster-management
sources:
- https://github.com/kubernetes/ingress-nginx
version: 0.7.0
